# Generated by Django 2.2.4 on 2020-05-20 14:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_auto_20190717_2205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='exam_creation_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 20, 22, 5, 8, 720953)),
        ),
        migrations.AlterField(
            model_name='takenexam',
            name='done_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 20, 22, 5, 8, 724461)),
        ),
    ]
